          PARAMETER (NMAX=132000,KMAX=1,MMAX=KMAX*NMAX,
     .NWCMAX=550,MWCMAX=KMAX*NWCMAX,NWDMAX=9000,
     .NMAX1=NMAX+1,MMAX1=MMAX+1,NNWMAX=NMAX*NWCMAX,
     .MMWMAX=MMAX*MWCMAX,MMW2MX=MMWMAX/2,LLWMAX=MMW2MX)
*     .MMWMAX=MMAX*MWCMAX,MMW2MX=MMWMAX/2,LLWMAX=MAX(NNWMAX,MMW2MX))
          IMPLICIT DOUBLE PRECISION(A-H,O-Z) 
          CHARACTER*1 DATO,PCHAR,PTO,AST,BLANK
          CHARACTER*4 FORMA,TITOLO 
          CHARACTER*120 CDATO
          DIMENSION V(MMAX),Z(MMAX),LC(MMAX1),JC(LLWMAX),C(MMW2MX),
     .T(MMW2MX),ICOVA(MWCMAX,3),COVA(MWCMAX,3),KONT(NMAX1),
     .R(MMAX),U(MMAX),W(MMAX), 
     .X(NMAX),Y(NMAX),IPX(NMAX),IPY(NMAX),LPX(NMAX),LPY(NMAX), 
     .JCRONA(MMAX1),JCOVAS(LLWMAX),IBANDA(NMAX),JBANDA(NMAX),  
     .NUMERO(NMAX),INDIR(NMAX),
     .NOME(NMAX),NTIPO(NMAX),IWD(NWDMAX),IPUNT(NWDMAX),
     .DA(6),DB(6),DC(6),SNOISE(6),NCASO(6),DATO(120),PCHAR(120),IPTO(6),
     .IAST(3),IND(7),ICA(3,3,7),ISGN(2,6),AA(3,3),BB(3,3),CC(3,3),D(3), 
     .E(3),KP(3),LP(3),S1(3),S2(3),S3(3),S4(3),S5(3),S6(3),S7(3),S8(3), 
     .TGL(6),FORMA(20),TITOLO(20),ND(7,3),EC(3)


      print *,'Calcolo occupazione di memoria collop_sar'
      noccupa=LLWMAX*4+MMW2MX*8+MMW2MX*8+LLWMAX*4
      ntot=noccupa+56*NMAX+60*NMAX+MWCMAX*36
      print  '(''Occupazione di memoria = '',I10,I10)',
     . noccupa,ntot
      end

